CREATE SCHEMA o;
GO

CREATE TABLE o.Customers
(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Firstname NVARCHAR(100) NOT NULL,
	Lastname NVARCHAR(100) NOT NULL,
	CardNumber NVARCHAR(30) NOT NULL
);

CREATE TABLE o.Products
(
	Id INT IDENTITY (10,10) NOT NULL PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Price MONEY
);

CREATE TABLE o.Orders
(
	Id INT IDENTITY (100,100) NOT NULL PRIMARY KEY,
	ProductId INT NOT NULL FOREIGN KEY REFERENCES o.Products(Id),
	CustomerId INT NOT NULL FOREIGN KEY REFERENCES o.Customers(Id)
);
GO

-- data input goes below here
-- insert 3 values into Customers table
INSERT INTO o.Customers (Firstname, Lastname, CardNumber) VALUES
	('John', 'Smith', '0000000000000000');
INSERT INTO o.Customers (Firstname, Lastname, CardNumber) VALUES
	('Jane', 'Doe', '1111111111111111');
INSERT INTO o.Customers (Firstname, Lastname, CardNumber) VALUES
	('Bob', 'Ross', '7777777777777777');

-- insert 3 values into Products table
INSERT INTO o.Products (Name, Price) VALUES
	('Nintendo Switch', 300);
INSERT INTO o.Products (Name, Price) VALUES
	('OnePlus 6T', 579);
INSERT INTO o.Products (Name, Price) VALUES
	('Laptop', 1300);

-- insert 3 values into Orders table
INSERT INTO o.Orders (ProductId, CustomerId) VALUES
	(30, 1);
INSERT INTO o.Orders (ProductId, CustomerId) VALUES
	(20, 2);
INSERT INTO o.Orders (ProductId, CustomerId) VALUES
	(10, 3);

-- add product iPhone at price $200
INSERT INTO o.Products (Name, Price) VALUES
	('iPhone', 200);

-- add customer Tina Smith
INSERT INTO o.Customers (Firstname, Lastname, CardNumber) VALUES
	('Tina', 'Smith', '2222222222222222');

-- create order for Tina Smith bought an iPhone
INSERT INTO o.Orders (ProductId, CustomerId) VALUES
	(40, 4);

-- report all orders by Tina Smith
SELECT c.Id, c.Firstname, c.Lastname, ord.Id, ord.ProductId, p.Name, p.Price
FROM o.Customers AS c
	INNER JOIN o.Orders AS ord ON c.Id = ord.CustomerId
	INNER JOIN o.Products AS p ON ord.ProductId = p.Id
WHERE ord.CustomerId = 4;

-- report all revenue generated by sales of iPhone
SELECT SUM(p.Price)
FROM o.Products AS p
	INNER JOIN o.Orders AS ord ON p.Id = ord.ProductId
WHERE ord.ProductId = 40;

-- increase the price of iPhone to $250
UPDATE o.Products
	SET Price = 250
WHERE Name = 'iPhone';
SELECT * FROM o.Products;