CREATE SCHEMA Store
GO
CREATE TABLE Store.Products
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    Name NVARCHAR(128),
    Price FLOAT
)

CREATE TABLE Store.Customers
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    FirstName NVARCHAR(128),
    LastName NVARCHAR(128),
    CardNumber INT
)

CREATE TABLE Store.Orders
(
    ID INT IDENTITY PRIMARY KEY NOT NULL,
    ProductID INT FOREIGN KEY REFERENCES Store.Products (ID),
    CustomerID INT FOREIGN KEY REFERENCES Store.Customers (ID)
)

-- Add at least 3 records into each table

-- Adding records to Products table
INSERT INTO Store.Products(Name, Price)
    VALUES('Xbox', 300)
INSERT INTO Store.Products(Name, Price)
    VALUES('Wii', 200)
INSERT INTO Store.Products(Name, Price)
    VALUES('Playstation', 350)

-- Adding records to Customers table
INSERT INTO Store.Customers(FirstName, LastName, CardNumber)
    VALUES('John', 'Pot', 12345)
INSERT INTO Store.Customers(FirstName, LastName, CardNumber)
    VALUES('Hank', 'Hill', 23456)
INSERT INTO Store.Customers(FirstName, LastName, CardNumber)
    VALUES('Dale', 'Gribble', 34567)

-- Adding recoreds to Orders table
INSERT INTO Store.Orders(ProductID, CustomerID)
    -- Xbox, John
    VALUES(1, 1)
INSERT INTO Store.Orders(ProductID, CustomerID)
    -- Wii, Hank
    VALUES(2, 2)
INSERT INTO Store.Orders(ProductID, CustomerID)
    -- Playstation, Dale
    VALUES(3, 3)

-- Adding a new product iPhone priced at 200
INSERT INTO Store.Products(Name, Price)
    VALUES('iPhone', 200)

-- Adding new customer Tina Smith
INSERT INTO Store.Customers(FirstName, LastName, CardNumber)
    VALUES('Tina', 'Smith', 98765)

-- Creating order for Tina Smith buying iPhone
INSERT INTO Store.Orders(ProductID, CustomerID)
    -- Tina, iPhone
    VALUES(4, 4)

-- Report all orders by Tina Smith
SELECT * FROM Store.Orders 
-- Tina ID is 4
WHERE Store.Orders.CustomerID = 4

-- Report all revenue generated by sales of iPhone
SELECT SUM(products.Price)
FROM Store.Orders AS orders
    INNER JOIN Store.Products AS products ON products.ID = orders.ProductID
WHERE products.Name = 'iPhone' 

-- Increase the price of iPhone to 250
UPDATE Store.Products
SET Price = 250
WHERE Name = 'iPhone'